# Coding_neurons_and_layers


In [3]:
# Neuron with 3 inputs
inputs = [1, 2, 3]
weights = [0.2, -0.4, 0.8]
bias = 2
result = (inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias)
print(result)

3.8000000000000003


In [4]:

# Neuron with 4 inputs
inputs = [1, 2, 3, 4]
weights = [0.2, -0.4, 0.8, -0.71]
bias = 3
result = (inputs[0]*weights[0] +
          inputs[1]*weights[1] +
          inputs[2]*weights[2] +
          inputs[3]*weights[3] + bias)
print(result)

1.9600000000000004


# Cool now do a layer

In [5]:
# Layer of 3 neurons each with 5 inputs
inputs = [2, 4, 0.5, -3, 5]

w = [[1, 2, 3, 4, 5],
     [2, 3, 4, 5, 6],
    [3, 4, 5, 6, 7]]

bias = [2, 5, -6]

results = []
for i in range(len(w)):
    temp = 0
    for j in range(len(w[i])):
        temp += inputs[j]*w[i][j]
    results.append(temp + bias
        [i])
    
print(results)

[26.5, 38.0, 35.5]


# better looping in python

In [6]:
# Layer of 3 neurons each with 5 inputs but with more verbose and less i using loops
inputs = [2, 4, 0.5, -3, 5]

weights = [[1, 2, 3, 4, 5],
     [2, 3, 4, 5, 6],
    [3, 4, 5, 6, 7]]

biases = [2, 5, -6]

layer_outputs = []

for neuron_weight, neuron_bias in zip(weights, biases):
    result = 0
    for weight, n_input in zip(neuron_weight, inputs):
        result += weight*n_input
    layer_outputs.append(result + neuron_bias)
print(layer_outputs)

[26.5, 38.0, 35.5]


# Now same thing but in Numpy

In [10]:
import numpy as np


In [8]:
# Coding a neuron in numpy
inputs = np.array([2, 4, 0.5, -3, 5])
weights = np.array([1, 2, 3, 4, 5])
bias = 2

result = np.dot(weights, inputs.reshape(len(inputs), 1)) + bias

print(result)


[26.5]


In [9]:
# Coding a layer of neurons in numpy
inputs = np.array([2, 4, 0.5, -3, 5])

weights = np.array([[1, 2, 3, 4, 5],
                    [2, 3, 4, 5, 6],
                    [3, 4, 5, 6, 7]])

biases = np.array([2, 5, -6])

layer_outputs = np.dot(inputs, weights.T) + biases
print(layer_outputs)



[26.5 38.  35.5]


In [10]:
# Coding a batch of inputs being fed to a layer of neurons in numpy
inputs = np.array([[2, 4, 0.5, -3, 5],
                   [1, 67, 32, -90, 6],
                   [34, 65, -97, -12, -5]])

weights = np.array([[1, 2, 3, 4, 5],
                    [2, 3, 4, 5, 6], 
                    [3, 4, 5, 6, 7]])

biases = np.array([2, 5, -6])

layer_outputs = np.dot(inputs, weights.T) + biases
print(layer_outputs)

[[  26.5   38.    35.5]
 [ -97.   -78.   -73. ]
 [-198.  -210.  -236. ]]


# A forward pass thingy without activation (2 hidden layers of neuron with batch inputs)

In [11]:
# Coding a batch of inputs being fed to a layer of neurons in numpy
inputs = np.array([[2, 4, 0.5, -3, 5],
                   [1, 67, 32, -90, 6],
                   [34, 65, -97, -12, -5]])

# layer 1
weights1 = np.array([[1, 2, 3, 4, 5],
                    [2, 3, 4, 5, 6], 
                    [3, 4, 5, 6, 7]])

biases1 = np.array([2, 5, -6])

# layer 2
weights2 = np.array([[1, 2, 3],
                    [2, 3, 6], 
                    [3, 6, 7]])

biases2 = np.array([2, 5, -6])


layer_outputs_1 = np.dot(inputs, weights1.T) + biases1
layer_outputs_2 = np.dot(layer_outputs_1, weights2.T) + biases2

print(layer_outputs_2)

[[  211.   385.   550.]
 [ -470.  -861. -1276.]
 [-1324. -2437. -3512.]]


# Dense Layer Class

In [1]:
import nnfs
from nnfs.datasets import spiral_data
from nnfs.datasets import vertical_data
nnfs.init()
# Dense Layer
class DenseLayer:
    def __init__(self, n_inputs, n_neurons):
        # initializes the weights
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.outputs = np.dot(inputs, self.weights) + self.biases

X, y = spiral_data(samples=200, classes=4)

dense1 = DenseLayer(2, 3)
dense1.forward(X)
print(dense1.outputs[:5])
    

NameError: name 'np' is not defined

# ReLu Class

In [13]:
# ReLU class

class Activation_ReLU:
    def forward(self, inputs):
        self.outputs = np.maximum(0, inputs)
        

# Softmax Function

In [14]:
# Softmax activation

class Activation_Softmax:
    def forward(self, inputs):
        exp_inputs = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_inputs / np.sum(exp_inputs, axis=1, keepdims=True)
        self.outputs = probabilities        


# Full pass without Loss

In [15]:
# Full pass without Loss
X, y = spiral_data(samples=100, classes=3)

inputs = [[1, 7], [13, 4], [54, 3]]

dense1 = DenseLayer(2, 3)

activation1 = Activation_ReLU()

dense2 = DenseLayer(3, 3)

activation2 = Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.outputs)
dense2.forward(activation1.outputs)
activation2.forward(dense2.outputs)

print(activation2.outputs[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.3333337  0.3333326  0.33333373]
 [0.33333346 0.33333284 0.33333364]
 [0.33333457 0.3333309  0.33333457]
 [0.33333477 0.3333303  0.33333492]]


# Loss Functions


In [16]:
class Loss:

    def calculate(self, output, y):
        sample_losses = self.forward(output, y)
        data_loss = np.mean(sample_losses)
        return data_loss

In [3]:
# Loss Function

class Loss_CategoricalCrossentropy(Loss):
    def forward(self, y_pred, y_true):
        y_pred_clipped = np.clip(y_pred, 1e-7, 1 - 1e-7)
        if len(y_true.shape) == 1:
            correct_confidences = y_pred_clipped[range(len(y_pred)), y_true]
        elif len(y_true.shape) == 2: 
            correct_confidences = np.sum(y_true*y_pred_clipped, axis=1)
             
        negative_log_likelihoods = -np.log(correct_confidences)
        return negative_log_likelihoods
    
    

# One forward Pass with Loss

In [18]:
# Full pass without Loss
X, y = spiral_data(samples=100, classes=3)

inputs = [[1, 7], [13, 4], [54, 3]]

dense1 = DenseLayer(2, 3)

activation1 = Activation_ReLU()

dense2 = DenseLayer(3, 3)

activation2 = Activation_Softmax()

loss_function = Loss_CategoricalCrossentropy()

dense1.forward(X)
activation1.forward(dense1.outputs)
dense2.forward(activation1.outputs)
activation2.forward(dense2.outputs)
loss = loss_function.calculate(activation2.outputs, y)

print(activation2.outputs[:5])

print("loss: ", loss)

predictions = np.argmax(activation2.outputs, axis=1)
if len(y.shape) == 2:
    y = np.argmax(y, axis=1)
accuracy = np.mean(predictions == y)

print("accuracy: ", accuracy)


[[0.33333334 0.33333334 0.33333334]
 [0.3333336  0.33333302 0.3333333 ]
 [0.3333341  0.3333326  0.33333334]
 [0.3333355  0.33333147 0.33333305]
 [0.33333603 0.33333093 0.333333  ]]
loss:  1.0986149
accuracy:  0.3333333333333333


# Optimizing the neural network

In [19]:
# Random values of weights and biases hoping for better results
X, y = spiral_data(samples=100, classes=3)

dense1 = DenseLayer(2, 3)
activation1 = Activation_ReLU()
dense2 = DenseLayer(3, 3)
activation2 = Activation_Softmax()
loss_function = Loss_CategoricalCrossentropy()


# some helper variables
lowest_loss = 9999999
iter = 0
lowest_dense1_weights = dense1.weights.copy()
lowest_dense1_biases = dense1.biases.copy()
lowest_dense2_weights = dense2.weights.copy()
lowest_dense2_biases = dense2.biases.copy()


for i in range(10000):
    dense1.weights += 0.05 * np.random.randn(2, 3)
    dense1.biases += 0.05 * np.random.rand(1, 3)
    dense2.weights += 0.05 * np.random.randn(3, 3)
    dense2.biases += 0.05 * np.random.rand(1, 3)
    
    dense1.forward(X)
    activation1.forward(dense1.outputs)
    dense2.forward(activation1.outputs)
    activation2.forward(dense2.outputs)
    loss = loss_function.calculate(activation2.outputs, y)

    predictions = np.argmax(activation2.outputs, axis=1)
    if len(y.shape) == 2:
        y = np.argmax(y, axis=1)
    accuracy = np.mean(predictions == y)
    iter+=1
    if loss < lowest_loss:
        lowest_dense1_weights = dense1.weights.copy()
        lowest_dense1_biases = dense1.biases.copy()
        lowest_dense2_weights = dense2.weights.copy()
        lowest_dense2_biases = dense2.biases.copy() 
        print("loss: ", loss, 'acc: ', accuracy, "iter: ", iter)
        lowest_loss = loss



loss:  1.0986782 acc:  0.3333333333333333 iter:  1
loss:  1.0986092 acc:  0.3333333333333333 iter:  10


In [20]:
# Randomly adjusting values of weights and biases
import nnfs
from nnfs.datasets import vertical_data
X, y = vertical_data(samples=100, classes=3)
print(2)
dense1 = DenseLayer(2, 3)
activation1 = Activation_ReLU()
dense2 = DenseLayer(3, 3)
activation2 = Activation_Softmax()
loss_function = Loss_CategoricalCrossentropy()


# some helper variables
lowest_loss = 9999999
lowest_dense1_weights = dense1.weights.copy()
lowest_dense1_biases = dense1.biases.copy()
lowest_dense2_weights = dense2.weights.copy()
lowest_dense2_biases = dense2.biases.copy()


for i in range(1000):
    dense1.weights += 0.01 * np.random.randn(2, 3)
    dense1.biases += 0.01 * np.random.rand(1, 3)
    dense2.weights += 0.01 * np.random.randn(3, 3)
    dense2.biases += 0.01 * np.random.rand(1, 3)
    
    dense1.forward(X)
    activation1.forward(dense1.outputs)
    dense2.forward(activation1.outputs)
    activation2.forward(dense2.outputs)
    loss = loss_function.calculate(activation2.outputs, y)

    predictions = np.argmax(activation2.outputs, axis=1)
    if len(y.shape) == 2:
        y = np.argmax(y, axis=1)
    accuracy = np.mean(predictions == y)
    if loss < lowest_loss:
        lowest_dense1_weights = dense1.weights.copy()
        lowest_dense1_biases = dense1.biases.copy()
        lowest_dense2_weights = dense2.weights.copy()
        lowest_dense2_biases = dense2.biases.copy() 
        if i % 10 == 0:
            print("loss: ", loss, 'acc: ', accuracy, "New set of best values found, iteration: ", i)
        lowest_loss = loss
    else:
        dense1.weights = lowest_dense1_weights.copy()
        dense1.biases = lowest_dense1_biases.copy()
        dense2.weights = lowest_dense2_weights.copy()
        dense2.biases = lowest_dense2_biases.copy()

2
loss:  1.098535 acc:  0.3333333333333333 New set of best values found, iteration:  0
loss:  1.0981333 acc:  0.3333333333333333 New set of best values found, iteration:  10
loss:  1.0951539 acc:  0.3333333333333333 New set of best values found, iteration:  30
loss:  1.0916325 acc:  0.36666666666666664 New set of best values found, iteration:  60
loss:  1.090195 acc:  0.3333333333333333 New set of best values found, iteration:  70
loss:  1.0854732 acc:  0.3333333333333333 New set of best values found, iteration:  90
loss:  1.0821099 acc:  0.3333333333333333 New set of best values found, iteration:  100
loss:  1.073277 acc:  0.3333333333333333 New set of best values found, iteration:  120
loss:  1.0683508 acc:  0.35 New set of best values found, iteration:  130
loss:  1.0588216 acc:  0.38 New set of best values found, iteration:  150
loss:  1.0529004 acc:  0.45 New set of best values found, iteration:  170
loss:  1.0470719 acc:  0.55 New set of best values found, iteration:  180
loss:  

# Backpropogation through a whole Layer (We are geting somewhere)

In [21]:
def ReLU(inputs):
    return np.maximum(0, inputs)

def ReLU_derivative(x):
    return np.where(x > 0, 1.0, 0.0)

inputs = np.array([1, 2, 3, 4])
weights = np.array([[0.1, 0.2, 0.3, 0.4],
                    [0.5, 0.6, 0.7, 0.8], 
                    [0.9, 1.0, 1.1 ,1.2]])
bias = np.array([0.1, 0.2, 0.3])
learning_rate = 0.001
target_output = 0.0

for i in range(200):
    z = np.dot(weights, inputs) + bias
    a = ReLU(z)
    y = np.sum(a)

    # Loss
    loss = y ** 2
    dL_dy = 2 * y
    dy_da = np.ones_like(a)
    
    dL_da = dL_dy * dy_da
    
    da_dz = ReLU_derivative(a)

    dL_dz = dL_da * da_dz
    
    dL_dw = np.outer(dL_dz, inputs)
    dL_db = dL_dz

    # Updating weights and bias
    weights -= learning_rate * dL_dw 
    bias -= learning_rate * dL_db
    if i % 20 == 0:
        print("Iteration: ", i, "Loss: ", loss)

Iteration:  0 Loss:  466.56000000000006
Iteration:  20 Loss:  5.329595763793193
Iteration:  40 Loss:  0.41191524253483786
Iteration:  60 Loss:  0.03183621475376345
Iteration:  80 Loss:  0.002460565405431671
Iteration:  100 Loss:  0.0001901729121621426
Iteration:  120 Loss:  1.4698120139337557e-05
Iteration:  140 Loss:  1.1359948840900371e-06
Iteration:  160 Loss:  8.779778427447647e-08
Iteration:  180 Loss:  6.785903626216421e-09


# Using Matrices in this back prpogation

In [22]:
# Matrices easen the process


# FOR GRADIENT OF LOSS WRT  WEIGHTS
# dL_dw = dL_dz Matrix Multiplication dz_dw
# dz_dw = inputs
# dL_dw = dL_dz Matrix Multiplication inputs
# now dL_dz is a matrix like 1 x n and inputs is a matrix of size 1 x n
# so we matrix multiply transpose(weights) AND dL_dz
# This gives you the dL_dw matrix a single column is the gradients of the weights of a single neuron and the multiple columns are multiple neurons, SO A LAYER OF NEURONS
# X_transpose * dL_dz

d_values = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
inputs = np.array([[1, 2, 3, 2.5], [2., 5. , -1., 2], [-1.5, 2.7 ,3.3, -0.8]])

dweights = np.dot(inputs.T, d_values)

print(dweights)



[[ 0.5  0.5  0.5]
 [20.1 20.1 20.1]
 [10.9 10.9 10.9]
 [ 4.1  4.1  4.1]]


In [23]:
# FOR GRADIENT OF LOSS WRT BIAS
# dL_db = dL_dz

dvalues = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])

biases = np.array([2, 3 ,0.5])

dbiases = np.sum(dvalues, axis=0, keepdims=True)

print(dbiases)

[[6 6 6]]


In [24]:
# FOR GRADIENT OF LOSS WRT INPUTS
# ans = transpose(input) * dz_da
# THIS CODE ->>>>>


dvalues = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])

weights = np.array([[0.2, 0.8 ,-0.5, 1], [0.5, -0.91, 0.26 ,-0.5], [-0.26, -0.27, -0.17, -0.87]]).T

dinputs = np.dot(dvalues, weights.T)

print(dinputs)

[[ 0.44 -0.38 -0.41 -0.37]
 [ 0.88 -0.76 -0.82 -0.74]
 [ 1.32 -1.14 -1.23 -1.11]]


In [25]:
# Dense Layer
class DenseLayer:
    def __init__(self, n_inputs, n_neurons):
        # initializes the weights
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.inputs = inputs
        self.outputs = np.dot(inputs, self.weights) + self.biases
    def backward(self, dvalues):
        self.dweights = np.dot(self.inputs.T, dvalues)
        self.dinputs = np.dot(dvalues, self.weights.T)
        self.dbiases = np.sum(dvalues, axis=0, keepdims=True)
        

In [12]:
# ReLU class

class Activation_ReLU:
    def forward(self, inputs):
        self.inputs = inputs
        self.outputs = np.maximum(0, inputs)
    def backward(self, dvalues):
        self.dinputs = dvalues.copy()
        self.dinputs[self.inputs <= 0] = 0
        

In [27]:
# Loss Function

class Loss_CategoricalCrossentropy(Loss):
    def forward(self, y_pred, y_true):
        y_pred_clipped = np.clip(y_pred, 1e-7, 1 - 1e-7)
        if len(y_true.shape) == 1:
            correct_confidences = y_pred_clipped[range(len(y_pred)), y_true]
        elif len(y_true.shape) == 2: 
            correct_confidences = np.sum(y_true*y_pred_clipped, axis=1)
             
        negative_log_likelihoods = -np.log(correct_confidences)
        return negative_log_likelihoods

    def backward(self, dvalues, y_true):
        samples = len(dvalues)
        labels = len(dvalues[0])
        if len(y_true.shape) == 1:
            # One Hot Encoding
            y_true = np.eye(labels)[y_true]
        self.dinputs = - y_true / dvalues
        # Normalization
        self.dinputs = self.dinputs / samples

In [5]:
# Softmax activation

class Activation_Softmax:
    def forward(self, inputs):
        exp_inputs = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_inputs / np.sum(exp_inputs, axis=1, keepdims=True)
        self.outputs = probabilities        

In [6]:
# Softmax Classifier - combined with softax activation
# and cross-entropy loss for faster backward step

class Activation_Softmax_Loss_CategoricalCrossEntropy:
    def __init__(self):
        self.activation = Activation_Softmax()
        self.loss = Loss_CategoricalCrossentropy()

    def forward(self, inputs, y_true):
        self.activation.forward(inputs)
        self.outputs = self.activation.outputs

        return self.loss.calculate(self.outputs, y_true)

    def backward(self, dvalues, y_true):
        samples = len(dvalues)
        if len(y_true.shape) == 2:
            # One Hot Encoding
            y_true = np.argmax(y_true, axis=1)
        self.dinputs = dvalues.copy()

        self.dinputs[range(samples), y_true] -= 1
        self.dinputs = self.dinputs / samples

In [30]:
X, y = spiral_data(classes=3, samples=100)

dense1 = DenseLayer(2, 3)
activation1 = Activation_ReLU()
dense2 = DenseLayer(3, 3)
loss_activation = Activation_Softmax_Loss_CategoricalCrossEntropy()

for i in range(2):
    dense1.forward(X)
    activation1.forward(dense1.outputs)
    dense2.forward(activation1.outputs)
    loss = loss_activation.forward(dense2.outputs, y)
    
    print("Loss: ", loss)
    print("Output: ", loss_activation.outputs[:2])

    predictions = np.argmax(loss_activation.outputs, axis=1)
    if len(y.shape) == 2:
        y = np.argmax(y, axis=1)
    acc = np.mean(predictions == y)

    print("Accuracy: ", acc)

    
    loss_activation.backward(loss_activation.outputs, y)
    dense2.backward(loss_activation.dinputs)
    activation1.backward(dense2.dinputs)
    dense1.backward(activation1.dinputs)

    print(dense1.dweights)    
    print(dense1.dbiases)
    print(dense2.dweights)
    print(dense2.dbiases)
    print()
    print()

Loss:  1.0986137
Output:  [[0.33333334 0.33333334 0.33333334]
 [0.3333332  0.33333337 0.33333334]]
Accuracy:  0.30333333333333334
[[ 9.1763563e-05 -1.0102931e-04 -2.3483712e-05]
 [-1.9180491e-04  5.0279952e-05 -3.1159929e-05]]
[[ 2.9173034e-04  1.4010203e-04 -5.6438861e-05]]
[[-2.8359846e-05  1.4472018e-05  1.3887829e-05]
 [ 1.4806271e-04  1.2316163e-04 -2.7122436e-04]
 [-2.4048159e-05  1.2830078e-05  1.1218081e-05]]
[[ 1.8555438e-06 -7.2875991e-08 -1.9639265e-06]]


Loss:  1.0986137
Output:  [[0.33333334 0.33333334 0.33333334]
 [0.3333332  0.33333337 0.33333334]]
Accuracy:  0.30333333333333334
[[ 9.1763563e-05 -1.0102931e-04 -2.3483712e-05]
 [-1.9180491e-04  5.0279952e-05 -3.1159929e-05]]
[[ 2.9173034e-04  1.4010203e-04 -5.6438861e-05]]
[[-2.8359846e-05  1.4472018e-05  1.3887829e-05]
 [ 1.4806271e-04  1.2316163e-04 -2.7122436e-04]
 [-2.4048159e-05  1.2830078e-05  1.1218081e-05]]
[[ 1.8555438e-06 -7.2875991e-08 -1.9639265e-06]]




# Optimizers in Neural Networks

In [1]:
class Gradient_SGD:
    def __init__(self, learning_rate=1):
        self.learning_rate = learning_rate
    def update_params(self, layer1):
        layer1.weights -= self.learning_rate * layer1.dweights
        layer1.biases -= self.learning_rate * layer1.dbiases

In [ ]:
# Adding Optimizers in the current implementation
X, y = spiral_data(classes=3, samples=100)
print(2)
dense1 = DenseLayer(2, 64)
activation1 = Activation_ReLU()
dense2 = DenseLayer(64, 3)
loss_activation = Activation_Softmax_Loss_CategoricalCrossEntropy()
optimizer = Gradient_SGD()

for epoch in range(10000):
    # Forward Pass
    dense1.forward(X)
    activation1.forward(dense1.outputs)
    dense2.forward(activation1.outputs)
    loss = loss_activation.forward(dense2.outputs, y)

    predictions = np.argmax(loss_activation.outputs, axis=1)
    if len(y.shape) == 2:
        y = np.argmax(y, axis=1)
    acc = np.mean(predictions == y)

    # Back Pass
    loss_activation.backward(loss_activation.outputs, y)
    dense2.backward(loss_activation.dinputs)
    activation1.backward(dense2.dinputs)
    dense1.backward(activation1.dinputs)

    
    if not epoch % 1000:
        print(f'epoch: {epoch}, ' + 
              f'acc: {acc:.3f}' + 
              f'loss: {loss:.3f}')
    
    # Optimization
    optimizer.update_params(dense1)
    optimizer.update_params(dense2)
    

# Decay Gradient Descent

In [2]:
class Gradient_SDG_wdecay:
    def __init__(self, learning_rate=1., decay=0.):
        self.learning_rate = learning_rate
        self.current_learning_rate = learning_rate
        self.decay = decay
        self.iterations = 0
    def pre_update_params(self):
        if self.decay:
            self.current_learning_rate = self.learning_rate * \
            (1. /( 1. + self.decay * self.iterations))
            
    def update_params(self, layer):
        layer.weights -= self.current_learning_rate * layer.dweights
        layer.biases -= self.current_learning_rate * layer.dbiases

    def post_update_params(self):
        self.iterations += 1
    

In [31]:
# Adding a Momentum Gradient Descent Optimizer in the current implementation
X, y = spiral_data(classes=3, samples=100)
dense1 = DenseLayer(2, 64)
activation1 = Activation_ReLU()
dense2 = DenseLayer(64, 3)
loss_activation = Activation_Softmax_Loss_CategoricalCrossEntropy()
optimizer = Gradient_SDG_wdecay(1, 1e-3)

for epoch in range(10000):
    # Forward Pass
    dense1.forward(X)
    activation1.forward(dense1.outputs)
    dense2.forward(activation1.outputs)
    loss = loss_activation.forward(dense2.outputs, y)

    predictions = np.argmax(loss_activation.outputs, axis=1)
    if len(y.shape) == 2:
        y = np.argmax(y, axis=1)
    acc = np.mean(predictions == y)

    # Back Pass
    loss_activation.backward(loss_activation.outputs, y)
    dense2.backward(loss_activation.dinputs)
    activation1.backward(dense2.dinputs)
    dense1.backward(activation1.dinputs)

    
    if not epoch % 1000:
        print(f'epoch: {epoch}, ' + 
              f'acc: {acc:.3f}' + 
              f'loss: {loss:.3f}' +
              f'lr: {optimizer.current_learning_rate}')
    
    # Optimization
    optimizer.pre_update_params()
    optimizer.update_params(dense1)
    optimizer.update_params(dense2)
    optimizer.post_update_params()

epoch: 0, acc: 0.300loss: 1.099lr: 1
epoch: 1000, acc: 0.413loss: 1.048lr: 0.5002501250625312
epoch: 2000, acc: 0.437loss: 1.003lr: 0.33344448149383127
epoch: 3000, acc: 0.493loss: 0.952lr: 0.25006251562890724
epoch: 4000, acc: 0.513loss: 0.919lr: 0.2000400080016003
epoch: 5000, acc: 0.533loss: 0.900lr: 0.16669444907484582
epoch: 6000, acc: 0.537loss: 0.879lr: 0.1428775539362766
epoch: 7000, acc: 0.553loss: 0.862lr: 0.12501562695336915
epoch: 8000, acc: 0.587loss: 0.846lr: 0.11112345816201799
epoch: 9000, acc: 0.593loss: 0.832lr: 0.1000100010001


# Momentum Optimizer

In [32]:
class Gradient_SDG_Momentum:
    def __init__(self, learning_rate=1., decay=0., momentum=0.):
        self.learning_rate = learning_rate
        # current learing rate is the one with alpha
        self.current_learning_rate = learning_rate
        self.decay = decay
        self.iterations = 0
        self.momentum = momentum

    # Call once before updation
    def pre_update_params(self):
        if self.decay:
            self.current_learning_rate = self.learning_rate * \
            (1. /( 1. + self.decay * self.iterations))
            
    def update_params(self, layer):
        if self.momentum:
            if not hasattr(layer, "weight_momentums"):
                layer.weight_momentums = np.zeros_like(layer.weights)
                layer.bias_momentums = np.zeros_like(layer.biases)
                
            weight_updates = self.momentum * layer.weight_momentums - \
                            self.current_learning_rate* layer.dweights
            layer.weight_momentums = weight_updates

            bias_updates = self.momentum * layer.bias_momentums - \
                            self.current_learning_rate* layer.dbiases
            layer.bias_momentums = bias_updates
            
        else:
            weight_updates = -self.current_learning_rate * layer.dweights
            bias_updates = -self.current_learning_rate * layer.dbiases

        layer.weights += weight_updates
        layer.biases += bias_updates
    # Call once after updation
    def post_update_params(self):
        self.iterations += 1
    

In [33]:
# Trying the whole thing with Momentum Optimizer
# Adding a Momentum Gradient Descent Optimizer in the current implementation
X, y = spiral_data(classes=3, samples=100)
dense1 = DenseLayer(2, 64)
activation1 = Activation_ReLU()
dense2 = DenseLayer(64, 3)
loss_activation = Activation_Softmax_Loss_CategoricalCrossEntropy()
optimizer = Gradient_SDG_Momentum(decay=1e-3, momentum=0.7)

for epoch in range(10001):
    # Forward Pass
    dense1.forward(X)
    activation1.forward(dense1.outputs)
    dense2.forward(activation1.outputs)
    loss = loss_activation.forward(dense2.outputs, y)

    predictions = np.argmax(loss_activation.outputs, axis=1)
    if len(y.shape) == 2:
        y = np.argmax(y, axis=1)
    acc = np.mean(predictions == y)

    # Back Pass
    loss_activation.backward(loss_activation.outputs, y)
    dense2.backward(loss_activation.dinputs)
    activation1.backward(dense2.dinputs)
    dense1.backward(activation1.dinputs)

    if not epoch % 1000:
        print(f'epoch: {epoch}, ' + 
              f'acc: {acc:.3f}' + 
              f'loss: {loss:.3f}' +
              f'lr: {optimizer.current_learning_rate}')
    
    # Optimization
    optimizer.pre_update_params()
    optimizer.update_params(dense1)
    optimizer.update_params(dense2)
    optimizer.post_update_params()

epoch: 0, acc: 0.373loss: 1.099lr: 1.0
epoch: 1000, acc: 0.490loss: 0.938lr: 0.5002501250625312
epoch: 2000, acc: 0.507loss: 0.882lr: 0.33344448149383127
epoch: 3000, acc: 0.547loss: 0.808lr: 0.25006251562890724
epoch: 4000, acc: 0.657loss: 0.746lr: 0.2000400080016003
epoch: 5000, acc: 0.663loss: 0.661lr: 0.16669444907484582
epoch: 6000, acc: 0.697loss: 0.608lr: 0.1428775539362766
epoch: 7000, acc: 0.743loss: 0.568lr: 0.12501562695336915
epoch: 8000, acc: 0.760loss: 0.534lr: 0.11112345816201799
epoch: 9000, acc: 0.790loss: 0.508lr: 0.1000100010001
epoch: 10000, acc: 0.800loss: 0.481lr: 0.09091735612328393


In [34]:
class Optimizer_Adagrad:
    def __init__(self, learning_rate=1., decay=0., epsilon=1e-7):
        self.learning_rate = learning_rate
        # current learing rate is the one with alpha
        self.current_learning_rate = learning_rate
        self.decay = decay
        self.epsilon = epsilon
        self.iterations = 0

    # Call once before updation
    def pre_update_params(self):
        if self.decay:
            self.current_learning_rate = self.learning_rate * \
            (1. /( 1. + self.decay * self.iterations))
            
    def update_params(self, layer):
        if not hasattr(layer, "weight_cache"):
            layer.weight_cache = np.zeros_like(layer.weights)
            layer.bias_cache = np.zeros_like(layer.biases)

        layer.weight_cache += layer.dweights**2
        layer.bias_cache += layer.dbiases**2
        
        layer.weights += -self.current_learning_rate * \
                        layer.dweights / \
                        (np.sqrt(layer.weight_cache) + self.epsilon)
        

        layer.biases += -self.current_learning_rate * \
                        layer.dbiases / \
                        (np.sqrt(layer.bias_cache) + self.epsilon)

    # Call once after updation
    def post_update_params(self):
        self.iterations += 1
    

In [35]:
# Trying the whole thing with ADAGRAD Optimizer
X, y = spiral_data(classes=3, samples=100)
dense1 = DenseLayer(2, 64)
activation1 = Activation_ReLU()
dense2 = DenseLayer(64, 3)
loss_activation = Activation_Softmax_Loss_CategoricalCrossEntropy()
optimizer = Optimizer_Adagrad(learning_rate=0.1, decay=1e-4)

for epoch in range(10001):
    # Forward Pass
    dense1.forward(X)
    activation1.forward(dense1.outputs)
    dense2.forward(activation1.outputs)
    loss = loss_activation.forward(dense2.outputs, y)

    predictions = np.argmax(loss_activation.outputs, axis=1)
    if len(y.shape) == 2:
        y = np.argmax(y, axis=1)
    acc = np.mean(predictions == y)

    # Back Pass
    loss_activation.backward(loss_activation.outputs, y)
    dense2.backward(loss_activation.dinputs)
    activation1.backward(dense2.dinputs)
    dense1.backward(activation1.dinputs)

    if not epoch % 1000:
        print(f'epoch: {epoch}, ' + 
              f'acc: {acc:.3f}' + 
              f'loss: {loss:.3f}' +
              f'lr: {optimizer.current_learning_rate:.3f}')
    
    # Optimization
    optimizer.pre_update_params()
    optimizer.update_params(dense1)
    optimizer.update_params(dense2)
    optimizer.post_update_params()

epoch: 0, acc: 0.333loss: 1.099lr: 0.100
epoch: 1000, acc: 0.660loss: 0.761lr: 0.091
epoch: 2000, acc: 0.677loss: 0.699lr: 0.083
epoch: 3000, acc: 0.683loss: 0.669lr: 0.077
epoch: 4000, acc: 0.703loss: 0.651lr: 0.071
epoch: 5000, acc: 0.713loss: 0.636lr: 0.067
epoch: 6000, acc: 0.730loss: 0.621lr: 0.063
epoch: 7000, acc: 0.760loss: 0.565lr: 0.059
epoch: 8000, acc: 0.773loss: 0.545lr: 0.056
epoch: 9000, acc: 0.770loss: 0.534lr: 0.053
epoch: 10000, acc: 0.770loss: 0.524lr: 0.050


In [36]:
class Optimizer_RMSPROP:
    def __init__(self, learning_rate=1., decay=0., epsilon=1e-7, rho=0.9):
        self.learning_rate = learning_rate
        # current learing rate is the one with alpha
        self.current_learning_rate = learning_rate
        self.decay = decay
        self.epsilon = epsilon
        self.iterations = 0
        self.rho = rho

    # Call once before updation
    def pre_update_params(self):
        if self.decay:
            self.current_learning_rate = self.learning_rate * \
            (1. /( 1. + self.decay * self.iterations))
            
    def update_params(self, layer):
        if not hasattr(layer, "weight_cache"):
            layer.weight_cache = np.zeros_like(layer.weights)
            layer.bias_cache = np.zeros_like(layer.biases)

        layer.weight_cache = (self.rho * layer.weight_cache) + ((1-self.rho) * layer.dweights**2)
        layer.bias_cache = (self.rho * layer.bias_cache) + ((1 - self.rho) * layer.dbiases**2)
        
        layer.weights += -self.current_learning_rate * \
                        layer.dweights / \
                        (np.sqrt(layer.weight_cache) + self.epsilon)
        

        layer.biases += -self.current_learning_rate * \
                        layer.dbiases / \
                        (np.sqrt(layer.bias_cache) + self.epsilon)

    # Call once after updation
    def post_update_params(self):
        self.iterations += 1
    

In [37]:
# Trying the whole thing with RMSPROP Optimizer
X, y = spiral_data(classes=3, samples=100)
dense1 = DenseLayer(2, 64)
activation1 = Activation_ReLU()
dense2 = DenseLayer(64, 3)
loss_activation = Activation_Softmax_Loss_CategoricalCrossEntropy()
optimizer = Optimizer_RMSPROP(learning_rate=0.02, decay=1e-5, rho=0.9999)

for epoch in range(10001):
    # Forward Pass
    dense1.forward(X)
    activation1.forward(dense1.outputs)
    dense2.forward(activation1.outputs)
    loss = loss_activation.forward(dense2.outputs, y)

    predictions = np.argmax(loss_activation.outputs, axis=1)
    if len(y.shape) == 2:
        y = np.argmax(y, axis=1)
    acc = np.mean(predictions == y)

    # Back Pass
    loss_activation.backward(loss_activation.outputs, y)
    dense2.backward(loss_activation.dinputs)
    activation1.backward(dense2.dinputs)
    dense1.backward(activation1.dinputs)

    if not epoch % 1000:
        print(f'epoch: {epoch}, ' + 
              f'acc: {acc:.3f}' + 
              f'loss: {loss:.3f}' +
              f'lr: {optimizer.current_learning_rate:.8f}')
    
    # Optimization
    optimizer.pre_update_params()
    optimizer.update_params(dense1)
    optimizer.update_params(dense2)
    optimizer.post_update_params()

epoch: 0, acc: 0.353loss: 1.099lr: 0.02000000
epoch: 1000, acc: 0.587loss: 0.852lr: 0.01980218
epoch: 2000, acc: 0.623loss: 0.792lr: 0.01960804
epoch: 3000, acc: 0.620loss: 0.802lr: 0.01941766
epoch: 4000, acc: 0.650loss: 0.731lr: 0.01923095
epoch: 5000, acc: 0.657loss: 0.688lr: 0.01904780
epoch: 6000, acc: 0.677loss: 0.623lr: 0.01886810
epoch: 7000, acc: 0.657loss: 0.649lr: 0.01869176
epoch: 8000, acc: 0.710loss: 0.555lr: 0.01851869
epoch: 9000, acc: 0.763loss: 0.524lr: 0.01834879
epoch: 10000, acc: 0.777loss: 0.491lr: 0.01818198


In [14]:
class Optimizer_Adam:
    def __init__(self, learning_rate=1., decay=0., epsilon=1e-7, beta1=0.9, beta2=0.999):
        self.learning_rate = learning_rate
        # current learing rate is the one with alpha
        self.current_learning_rate = learning_rate
        self.decay = decay
        self.epsilon = epsilon
        self.iterations = 0
        self.beta1 = beta1
        self.beta2 = beta2

    # Call once before updation
    def pre_update_params(self):
        if self.decay:
            self.current_learning_rate = self.learning_rate * (1. /( 1. + self.decay * self.iterations))
            
    def update_params(self, layer):
        if not hasattr(layer, "weight_cache"):
            layer.weight_momentums = np.zeros_like(layer.weights)
            layer.bias_momentums = np.zeros_like(layer.biases)
            layer.weight_cache = np.zeros_like(layer.weights)
            layer.bias_cache = np.zeros_like(layer.biases)

        layer.weight_cache = self.beta2 * layer.weight_cache + (1 - self.beta2) * (layer.dweights ** 2)
        layer.bias_cache   = self.beta2 * layer.bias_cache   + (1 - self.beta2) * (layer.dbiases ** 2)
        
        layer.weight_momentums = (self.beta1 * layer.weight_momentums) + ((1 - self.beta1) * layer.dweights)                                                                         
        layer.bias_momentums = (self.beta1 * layer.bias_momentums) + ((1 - self.beta1) * layer.dbiases)

        weight_momentums_updated = layer.weight_momentums / ((1 - self.beta1**(self.iterations+1)))
        bias_momentums_updated = layer.bias_momentums / ((1 - self.beta1**(self.iterations+1)))

        weight_cache_updated = layer.weight_cache / ((1 - self.beta2**(self.iterations+1)))
        bias_cache_updated = layer.bias_cache / ((1 - self.beta2**(self.iterations+1)))
        
        layer.weights += -self.current_learning_rate * \
                        weight_momentums_updated / \
                        (np.sqrt(weight_cache_updated) + self.epsilon)
        

        layer.biases += -self.current_learning_rate * \
                        bias_momentums_updated / \
                        (np.sqrt(bias_cache_updated) + self.epsilon)

    # Call once after updation
    def post_update_params(self):
        self.iterations += 1
    

In [39]:
# Trying the whole thing with Adam Optimizer (The real Thang)
X, y = spiral_data(classes=3, samples=100)
dense1 = DenseLayer(2, 64)
activation1 = Activation_ReLU()
dense2 = DenseLayer(64, 3)
loss_activation = Activation_Softmax_Loss_CategoricalCrossEntropy()
optimizer = Optimizer_Adam(learning_rate=0.02, decay=1e-5)

for epoch in range(10001):
    # Forward Pass
    dense1.forward(X)
    activation1.forward(dense1.outputs)
    dense2.forward(activation1.outputs)
    loss = loss_activation.forward(dense2.outputs, y)

    predictions = np.argmax(loss_activation.outputs, axis=1)
    if len(y.shape) == 2:
        y = np.argmax(y, axis=1)
    acc = np.mean(predictions == y)

    # Back Pass
    loss_activation.backward(loss_activation.outputs, y)
    dense2.backward(loss_activation.dinputs)
    activation1.backward(dense2.dinputs)
    dense1.backward(activation1.dinputs)

    if not epoch % 100:
        print(f'epoch: {epoch}, ' + 
              f'acc: {acc:.3f}' + 
              f'loss: {loss:.3f}' +
              f'lr: {optimizer.current_learning_rate:.8f}')
    
    # Optimization
    optimizer.pre_update_params()
    optimizer.update_params(dense1)
    optimizer.update_params(dense2)
    optimizer.post_update_params()

epoch: 0, acc: 0.333loss: 1.099lr: 0.02000000
epoch: 100, acc: 0.513loss: 0.902lr: 0.01998022
epoch: 200, acc: 0.610loss: 0.736lr: 0.01996028
epoch: 300, acc: 0.637loss: 0.670lr: 0.01994038
epoch: 400, acc: 0.753loss: 0.592lr: 0.01992052
epoch: 500, acc: 0.773loss: 0.525lr: 0.01990070
epoch: 600, acc: 0.793loss: 0.479lr: 0.01988091
epoch: 700, acc: 0.800loss: 0.450lr: 0.01986117
epoch: 800, acc: 0.847loss: 0.406lr: 0.01984147
epoch: 900, acc: 0.850loss: 0.378lr: 0.01982180
epoch: 1000, acc: 0.860loss: 0.356lr: 0.01980218
epoch: 1100, acc: 0.860loss: 0.338lr: 0.01978259
epoch: 1200, acc: 0.857loss: 0.326lr: 0.01976304
epoch: 1300, acc: 0.850loss: 0.314lr: 0.01974353
epoch: 1400, acc: 0.850loss: 0.306lr: 0.01972406
epoch: 1500, acc: 0.857loss: 0.298lr: 0.01970463
epoch: 1600, acc: 0.850loss: 0.293lr: 0.01968523
epoch: 1700, acc: 0.857loss: 0.287lr: 0.01966588
epoch: 1800, acc: 0.867loss: 0.282lr: 0.01964656
epoch: 1900, acc: 0.867loss: 0.278lr: 0.01962728
epoch: 2000, acc: 0.867loss: 0.2

In [8]:
# Dense Layer
class DenseLayer:
    def __init__(self, n_inputs, n_neurons, weight_regularization_l1=0., bias_regularization_l1=0., weight_regularization_l2=0., bias_regularization_l2=0.):
        # initializes the weights
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
        self.weight_regularization_l1 = weight_regularization_l1
        self.bias_regularization_l1 = bias_regularization_l1
        self.weight_regularization_l2 = weight_regularization_l2
        self.bias_regularization_l2 = bias_regularization_l2
        
    def forward(self, inputs):
        self.inputs = inputs
        self.outputs = np.dot(inputs, self.weights) + self.biases
        
    def backward(self, dvalues):
        self.dweights = np.dot(self.inputs.T, dvalues)
        self.dinputs = np.dot(dvalues, self.weights.T)
        self.dbiases = np.sum(dvalues, axis=0, keepdims=True)
                    
        # Changing weights and biases with respect to the regularization loss
        if self.weight_regularization_l1 > 0:
            dwL1 = np.ones_like(self.weights)
            dwL1[self.weights < 0] = -1
            self.dweights += self.weight_regularization_l1 * dwL1
        
        if self.bias_regularization_l1 > 0:
            dbL1 = np.ones_like(self.biases)
            dbL1[self.biases < 0] = -1
            self.dbiases = self.bias_regularization_l1 * dbL1
            
        if self.weight_regularization_l2 > 0:
            self.dweights += 2 * self.weight_regularization_l2 * self.weights

        if self.bias_regularization_l2 > 0:
            self.dbiases += 2 * self.bias_regularization_l2 * self.biases


In [18]:
# Common loss class
class Loss:
    # Regularization loss calculation
    def regularization_loss(self, layer):
        # 0 by default
        regularization_loss = 0

        # L1 regularization - weights
        # Calculate only when factor greater than 0
        if layer.weight_regularizer_l1 > 0:
            regularization_loss += layer.weight_regularizer_l1 * np.sum(np.abs(layer.weights))

        # L2 regularization - weights
        if layer.weight_regularizer_l2 > 0:
            regularization_loss += layer.weight_regularizer_l2 * np.sum(layer.weights * layer.weights)

        # L1 regularization - biases
        # Calculate only when factor greater than 0
        if layer.bias_regularizer_l1 > 0:
            regularization_loss += layer.bias_regularizer_l1 * np.sum(np.abs(layer.biases))

        # L2 regularization - biases
        if layer.bias_regularizer_l2 > 0:
            regularization_loss += layer.bias_regularizer_l2 * np.sum(layer.biases * layer.biases)

        return regularization_loss

    # Calculates the data and regularization losses
    # given model output and ground truth values
    def calculate(self, output, y):
        # Calculate sample losses
        sample_losses = self.forward(output, y)
        # Calculate mean loss
        data_loss = np.mean(sample_losses)
        # Return loss
        return data_loss

In [7]:
class Layer_Dropout:
    def __init__(self, rate):
        self.rate = 1 - rate
    
    def forward(self, inputs):
        self.inputs = inputs
        self.binary_mask = np.random.binomial(1, self.rate, size=inputs.shape) / self.rate
        self.outputs = inputs * self.binary_mask
    
    def backward(self, dvalues):
        self.dinputs = dvalues * self.binary_mask

In [17]:
# Trying the whole thing with L1/L2 regularization and Dropout
X, y = spiral_data(classes=3, samples=100)
#dense1 = DenseLayer(2, 64)
dense1 = DenseLayer(2, 64, weight_regularization_l2=5e-4, bias_regularization_l2=5e-4)
activation1 = Activation_ReLU()
dropout1 = Layer_Dropout(0.1)
dense2 = DenseLayer(64, 3)
loss_activation = Activation_Softmax_Loss_CategoricalCrossEntropy()
optimizer = Optimizer_Adam(learning_rate=0.05, decay=5e-5)

for epoch in range(10001):
    # Forward Pass
    dense1.forward(X)
    activation1.forward(dense1.outputs)
    dropout1.forward(activation1.outputs)
    dense2.forward(dropout1.outputs)

    #Loss Calculation
    data_loss = loss_activation.forward(dense2.outputs, y)
    regularization_loss = (
        loss_activation.loss.regularization_loss(dense1) +
        loss_activation.loss.regularization_loss(dense2)       
    )

    loss = data_loss + regularization_loss

    predictions = np.argmax(loss_activation.outputs, axis=1)
    if len(y.shape) == 2:
        y = np.argmax(y, axis=1)
    acc = np.mean(predictions == y)

    # Back Pass
    loss_activation.backward(loss_activation.outputs, y)
    dense2.backward(loss_activation.dinputs)
    dropout1.backward(dense2.dinputs)
    activation1.backward(dropout1.dinputs)
    dense1.backward(activation1.dinputs)

    if not epoch % 100:
        print(f'epoch: {epoch}, ' + 
              f'acc: {acc:.3f} ' + 
              f'data_loss: {loss:.3f} ' +
              f'regularization_loss: {loss:.3f} ' +
              f'total_loss: {loss:.3f} ' +
              f'lr: {optimizer.current_learning_rate:.8f}')
    
    # Optimization
    optimizer.pre_update_params()
    optimizer.update_params(dense1)
    optimizer.update_params(dense2)
    optimizer.post_update_params()

X_test, y_test = spiral_data(classes=3, samples=100)
dense1.forward(X_test)
activation1.forward(dense1.outputs)
dense2.forward(activation1.outputs)
loss = loss_activation.forward(dense2.outputs, y_test)

predictions = np.argmax(loss_activation.outputs, axis=1)
if len(y_test.shape) == 2:
    y_test = np.argmax(y_test, axis=1)
acc = np.mean(predictions == y_test)
print(f"evaluation, acc: {acc:.3f}, loss: {loss:3f}")




epoch: 0, acc: 0.347 data_loss: 1.099 regularization_loss: 1.099 total_loss: 1.099 lr: 0.05000000
epoch: 100, acc: 0.583 data_loss: 0.897 regularization_loss: 0.897 total_loss: 0.897 lr: 0.04975372
epoch: 200, acc: 0.637 data_loss: 0.826 regularization_loss: 0.826 total_loss: 0.826 lr: 0.04950740
epoch: 300, acc: 0.670 data_loss: 0.785 regularization_loss: 0.785 total_loss: 0.785 lr: 0.04926351
epoch: 400, acc: 0.653 data_loss: 0.777 regularization_loss: 0.777 total_loss: 0.777 lr: 0.04902201
epoch: 500, acc: 0.667 data_loss: 0.794 regularization_loss: 0.794 total_loss: 0.794 lr: 0.04878287
epoch: 600, acc: 0.697 data_loss: 0.772 regularization_loss: 0.772 total_loss: 0.772 lr: 0.04854605
epoch: 700, acc: 0.690 data_loss: 0.787 regularization_loss: 0.787 total_loss: 0.787 lr: 0.04831151
epoch: 800, acc: 0.690 data_loss: 0.707 regularization_loss: 0.707 total_loss: 0.707 lr: 0.04807923
epoch: 900, acc: 0.703 data_loss: 0.703 regularization_loss: 0.703 total_loss: 0.703 lr: 0.04784918
ep